New Player Badge: Uncommon
Developer Badge: Legendary
Question-Answered Stickers: Common
First Tester Badge: Legendary
Point Doubler: Rare
Point Tripler: Ultimate
Pro Science Bowler Badge: Legendary
DOE Autograph: Ultimate
For Real Science Bowler Badge: Mythic
Flex Pass: Legendary
Skip Pass: Rare
25-Questions-Answered Certificate: Common
50-Questions-Answered Certificate: Uncommon
100-Questions-Answered Certificate: Rare
250-Questions-Answered Certificate: Ultimate
500-Questions-Answered Certificate: Legendary
1000-Questions-Answered Certificate: Mythic
Frying Pan Badge: Mythic
Ritz Badge: Mythic
"Campbell Biology: 12th Edition": Common
"Campbell Biology: 11th Edition": Common
"Campbell Biology: 10th Edition": Common
"Tarbuck Earth Science: 13th Edition": Common
"Tarbuck Earth Science: 12th Edition": Common
"Tarbuck Earth Science: 11th Edition": Common
"Serway College Physics: 9th Edition": Common
"Serway College Physics: 8th Edition": Common
"Serway College Physics: 7th Edition": Common
Certified Grinder Badge: Mythic
"Air Force One's": Rare
AOPS Volume 2: Uncommon
AOPS Volume 1: Uncommon
AOPS Intermediate Algebra: Uncommon
AOPS Introduction to Algebra: Uncommon
AOPS Introduction to Geometry: Uncommon
AOPS Introduction to Counting and Probability: Uncommon
AOPS Introduction to Number Theory: Uncommon
AOPS Intermediate Counting and Probability: Uncommon
AOPS Precalculus: Uncommon
AOPS Calculus: Uncommon