.a:
- 'Campbell Biology: 12th Edition'
- 'Campbell Biology: 11th Edition'
- 'Campbell Biology: 10th Edition'
- 'Tarbuck Earth Science: 13th Edition'
- 'Tarbuck Earth Science: 12th Edition'
- 'Tarbuck Earth Science: 11th Edition'
- 'Serway College Physics: 9th Edition'
- 'Serway College Physics: 8th Edition'
- 'Serway College Physics: 7th Edition'
.aamc10:
- AOPS Volume 2
- AOPS Volume 1
- AOPS Intermediate Algebra
- AOPS Introduction to Algebra
- AOPS Introduction to Geometry
- AOPS Introduction to Counting and Probability
- AOPS Introduction to Number Theory
- AOPS Intermediate Counting and Probability
- AOPS Precalculus
- AOPS Calculus
